# describe how model should be run
model:
- id: "my_matlab_model"
  exec: "matlab"
  param_key: "%#"
  base_directory: "_matlab_model"
- par: -batch "funz_main_hiMCES(%1,%2, %3, %4, %5)"
- val: "time"
  unit: "s"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "time"
- val: "Vm"
  unit: "V"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "Vm"
- val: "iStim"
  unit: "mV"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "iStim"
- val: "Cai"
  unit: "mmol"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "Cai"
- val: "Force"
  unit: "mN/mm2"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "AT"
- val: "Lsarc"
  unit: "mol"
  method: "matlab"
  file: "job_data_amin2024.mat"
  id: "Lsarc"


# how model should be run and with what parameters
experiment:
- name: "mylatin_#" # '#' is to be replaced with id-number
  id: "mylatin"
  cwd: "_example_matlab"
  model: "my_matlab_model"
  parametrization: "latin_hybercube"
  cells: 1
  parameter_count: 5
  equation: "0.5 + x + np.heaviside(x-0.5, 0.0)*(x-0.5)"
  manifest: "simulation_manifest.csv"

# list biomarkers that should be calculated
biomarkers:
- target: "mylatin"
  file: "biomarkers.csv"
- biomarker: "MDP"
  unit: "default"
- biomarker: "APD90"
- biomarker: "APD60"
  unit: "ms"
- biomarker: "dv_dt_max"
  unit: "V/s"
- biomarker: "Max_Cai"
  unit: "mmol"
- biomarker: "Min_Cai"
  unit: "mmol"
- biomarker: "Rate_Cai"
  unit: "Hz"
- biomarker: "CL"
  unit: "ms"
- biomarker: "APA"
  unit: "mV"
- biomarker: "Peak"
  unit: "mV"
- biomarker: "RT1050"
  unit: "ms"
- biomarker: "RT1090"
  unit: "ms"
- biomarker: "DT9010"
  unit: "ms"
- biomarker: "RT10Peak"
  unit: "ms"
- biomarker: "CAI_DURATION"
  unit: "ms"
- biomarker: "CTD30"
  unit: "ms"
- biomarker: "CTD50"
  unit: "ms"
- biomarker: "CTD90"
  unit: "ms"
- biomarker: "Rate_AP"
  unit: "bpm"
- biomarker: "RAPP_APD"
  unit: "unitless"
- biomarker: "peakTension"
  unit: "mN/mm2"
- biomarker: "cellShortPerc"
  unit: "unitless"
- biomarker: "relaxTime50"
  unit: "ms"

# Contains list of calibrations that should be run
calibration:
- file: "biomarkers.csv"
# calibration condition, basic check, checks if nan or inf
- protocol: "nonan"
  fail_path: "discarded_because_of_nans.csv"
# calibration condition, check against biomarkers
- protocol: "range"
  input_data_path: "example_range.csv"
  fail_path: "discarded.csv"
  success_path: "selected.csv"


# describe how model should optimized
optimization:
- model: "my_matlab_model" #required: model name (not used yet)
  cwd: "_example_matlab" #required: current working directory (root of where to save results)
  dir_name: "runs" #required: Directory in cwd, where the each individual run is stored
  loss_type: "mse" #required, Loss (fitness/energy) function used. Options: "mse"
  target_file: "example_target.csv" #required (for mse): target biomarkers to calculate loss
  parameter_count: 5 # required
  algorithm: "StornPrice" #required, parameter update algorithm for optimization. Options: "StornPrice"
  bounds_file: "example_bounds.csv" #optional: limits for parameter values. Optionality depends on algorithm.
  x0: "example_x0.csv" #required, start point for optimization (recommended to have sane value)
  max_iter: 1000 #optional, maximum iteration allowed
  result_file: "result.txt" # required. results will be stored to this file
