# describe how model should be run
model:
- id: "my_matlab_model"
  exec: "/home/mr0661/software/openCARP/_build/bin/bench"
  param_key: "%#"
  base_directory: "/home/mr0661/projects/population_of_models/_model" # Directory that is copied for each 
- par: "--load-module '/home/mr0661/projects/population_of_models/_model/_amin2024.so'"
- par: "--duration 100000.0"
- par: "--dt 0.01"
- par: "--dt-out 0.1"
- par: "--numstim 0"
- par: "--validate"
- par: "--save-ini-file end_state.sv"
- par: "--save-ini-time 100000.0"
- par: "--fout=job_data_amin2024"
- par: "--read-ini-file=initial.sv"
- par: "--imp-par i_stim_on=1,ADP_TUNE=%1,Pi_ref_TUNE=%2,ap2_TUNE=%3,F1_TUNE=%4,F2_TUNE=%5"
- val: "time"
  method: "binary"
  file: "job_data_amin2024.t.bin"
- val: "Vm"
  method: "binary"
  file: "job_data_amin2024.Vm.bin"
- val: "Cai"
  method: "binary"
  file: "job_data_amin2024__amin2024.Cai.bin"
- val: "iStim"
  method: "openCARP_trace"
  file: "Trace_0.dat"
  header_file: "_amin2024_trace_header.txt"
  header_name: "i_stim"

# how model should be run and with what parameters
experiment:
- name: "mylatin_#" # '#' is to be replaced with id-number
  id: "mylatin"
  cwd: "/home/mr0661/projects/population_of_models/_example"
  model: "my_matlab_model"
  parametrization: "latin_hybercube"
  equation: "0.5 + x + np.heaviside(x-0.5, 0.0)*(x-0.5)" # range 0.5-2
  cells: 12
  parameter_count: 5
  manifest: "simulation_manifest.csv"

# list biomarkers that should be calculated
biomarkers:
- window_start: "90000"
  window_end: "100000"
  target: "mylatin"
  file: "biomarkers.csv"
- biomarker: "MDP"
- biomarker: "APD90"
- biomarker: "APD60"
- biomarker: "Max_Cai"
- biomarker: "Min_Cai"
- biomarker: "Rate_Cai"
- biomarker: "CL"
- biomarker: "APA"

# Contains list of calibrations that should be run
calibration:
- file: "biomarkers.csv"
  experiment: "mylatin"
# calibration condition, basic check, checks if nan or inf
- protocol: "nonan"
  fail_path: "discarded_because_of_nans.csv"
# calibration condition, check against biomarkers
- protocol: "range"
  input_data_path: "example_range.csv"
  fail_path: "discarded.csv"
  success_path: "selected.csv"
