# describe how model should be run
model:
- id: "my_matlab_model"
  exec: "/home/mr0661/software/openCARP/_build/bin/bench"
  param_key: "%#"
  base_directory: "/home/mr0661/projects/population_of_models/_model" # Directory that is copied for each 
- par: "--load-module '/home/mr0661/projects/population_of_models/_model/_amin2024.so'"
- par: "--duration 100000.0"
- par: "--dt 0.01"
- par: "--dt-out 0.1"
- par: "--numstim 0"
- par: "--validate"
- par: "--save-ini-file end_state.sv"
- par: "--save-ini-time 100000.0"
- par: "--fout=job_data_amin2024"
- par: "--read-ini-file=initial.sv"
- par: "--imp-par i_stim_on=1"
- val: "time"
  method: "binary"
  file: "job_data_amin2024.t.bin"
- val: "Vm"
  method: "binary"
  file: "job_data_amin2024.Vm.bin"
- val: "Cai"
  method: "binary"
  file: "job_data_amin2024__amin2024.Cai.bin"
- val: "iStim"
  method: "openCARP_trace"
  file: "Trace_0.dat"
  header_file: "_amin2024_trace_header.txt"
  header_name: "i_stim"

# how model should be run and with what parameters
experiment:
- name: "mylatin_#" # '#' is to be replaced with id-number
  id: "mylatin"
  cwd: "/home/mr0661/projects/population_of_models/_example"
  model: "my_matlab_model"
  parametrization: "latin_hybercube"
  cells: 2
  parameter_count: 2
  manifest: "simulation_manifest.csv"

# list biomarkers that should be calculated
biomarkers:
- id: "all_biomarkerss" # Id for this set of biomarkers
  window: "end-10:end"
  target: "mylatin"
  file: "biomarkers.csv"
- biomarker: "MDP"
- biomarker: "APD90"
- biomarker: "APD60"

# Contains list of calibrations that should be run
calibration:
# calibration condition, basic check, checks if nan or inf
- protocol: "nonan"
  if_fail: "discarded_because_of_nans"
  if_success: "continue"
# calibration condition, check against biomarkers
- protocol: "biomarker_range"
  biomarked_id: "all_biomarkerss"
  input_data_path: "/some/path/to/data.csv"
  if_fail: "discarded"
  if_success: "selected"
