# describe how model should be run
model:
- id: "my_matlab_model"
  exec: "matlab -run 'main_hiPSC_CM_CE.m'"
  param_key: "%#"
- par: "\"INa_g_max=%1, If_g_max*%2\""
- par: "--simulation_length=800"
- par: "--stimulated=true"
- id: "my_matlab_model2"
  exec: "matlab -run 'main_hiPSC_CM_CE.m'"
- par: "--simulation_length=800"
- par: "--stimulated=true"

# how model should be run and with what parameters
experiment:
- name: "mylatin_#" # '#' is to be replaced with id-number
  id: "mylatin"
  cwd: "/home/mr0661/random/tmp"
  model: "my_matlab_model"
  parametrization: "latin_hybercube"
  cells: 100
  parameter_count: 2
  manifest: "simulation_manifest.yaml"

# list biomarkers that should be calculated
biomarkers:
- id: "all_biomarkerss" # Id for this set of biomarkers
  window: "end-10s:end"
  target: "mylatin"
- biomarker: "MDP"
- biomarker: "APD90"
- biomarker: "APD60"

# Contains list of calibrations that should be run
calibration:
# calibration condition, basic check, checks if nan or inf
- protocol: "nonan"
  if_fail: "discarded_because_of_nans"
  if_success: "continue"
# calibration condition, check against biomarkers
- protocol: "biomarker_range"
  biomarked_id: "all_biomarkerss"
  input_data_path: "/some/path/to/data.csv"
  if_fail: "discarded"
  if_success: "selected"
